# Generated by Django 5.1.5 on 2025-04-02 02:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financas', '0002_categoria_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='data_transacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
